allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.0-rc.115"
  - "@effect/platform-node@4.0.0-rc.115"
  - "@effect/vitest@4.0.0-rc.115"
  - effect@4.0.0-rc.115
  - "@vitest/coverage-v8@5.0.1"
  - "@vitest/mocker@5.0.1"
  - "@vitest/spy@5.0.1"
  - vitest@5.0.1
  - "@vitest/pretty-format@5.0.1"
  - "@vitest/ui@5.0.1"
  - "@vitest/utils@5.0.1"
