// Generated by scripts/vendor-anti-slop.ts — do not edit by hand.
interface AntiSlopRule {
  readonly create: (context: never) => Record<string, never>
}

declare const antiSlopPlugin: {
  readonly meta: { readonly name: string }
  readonly rules: { readonly [ruleName: string]: AntiSlopRule }
}

export default antiSlopPlugin
