/**
 * Re-vendors the anti-slop oxlint plugin (https://github.com/dmmulroy/anti-slop) into
 * presets/lint/antislop/plugin.mjs.
 *
 * Anti-slop is deliberately not published to npm — upstream's distribution model is "copy the
 * source into your repo" — so Adamantite ships a bundled build instead of declaring a dependency.
 * The bundle inlines the plugin's only dependency (@oxlint/plugins, a small pure-JS,
 * dependency-free shim) so the vendored file is fully self-contained. That version is pinned by
 * upstream's lockfile; if upstream ever drops the lockfile, a re-vendor at the same PINNED_REF can
 * inline a different @oxlint/plugins version, so read re-vendor diffs with that in mind.
 *
 * Usage: bun run scripts/vendor-anti-slop.ts [ref]
 *
 * Clones upstream at the pinned commit (or the given ref), installs its dependencies, bundles
 * src/index.ts to ESM, and rewrites plugin.mjs and license.md. After bumping PINNED_REF, review the
 * upstream diff and update the rules in presets/lint/antislop.ts if rules were added, removed, or
 * renamed (the antislop preset test will catch a mismatch).
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"

const REPO_URL = "https://github.com/dmmulroy/anti-slop.git"
const PINNED_REF = "446268e5d15baa968eaec669ff65358d36ae6259"

const ref = process.argv[2] ?? PINNED_REF
const outDir = path.join(import.meta.dirname, "../presets/lint/antislop")

function run(command: string[], cwd: string) {
  const result = Bun.spawnSync(command, { cwd, stderr: "inherit" })

  if (result.exitCode !== 0) {
    throw new Error(`${command.join(" ")} failed in ${cwd}`)
  }

  return result.stdout.toString().trim()
}

const cloneDir = mkdtempSync(path.join(tmpdir(), "anti-slop-"))

try {
  run(["git", "clone", REPO_URL, "."], cloneDir)
  run(["git", "checkout", ref], cloneDir)
  const commit = run(["git", "rev-parse", "HEAD"], cloneDir)

  // Install the plugin's dependencies (just @oxlint/plugins) so the bundler
  // can inline them.
  run(["bun", "install", "--production"], cloneDir)

  const build = await Bun.build({
    entrypoints: [path.join(cloneDir, "src/index.ts")],
    format: "esm",
    target: "node",
  })
  if (!build.success) {
    throw new Error(`Bundling anti-slop failed: ${build.logs.map(String).join("\n")}`)
  }

  const [output] = build.outputs

  // Bun emits a `// <path>` comment per bundled module, relative to the
  // output location — which points into the temp clone dir and differs per
  // machine. Trim the prefix so re-vendoring produces stable diffs.
  const cloneDirPattern = new RegExp(`^// \\S*${path.basename(cloneDir)}/`, "gmu")
  const rawBundle = await output.text()
  const bundle = rawBundle.replace(cloneDirPattern, "// ")
  const banner = `// Vendored build of the anti-slop oxlint plugin.
// Source: https://github.com/dmmulroy/anti-slop (MIT) at commit ${commit}.
// Its @oxlint/plugins dependency (MIT) is inlined so this file is
// self-contained. See license.md for the full license text.
//
// Generated by scripts/vendor-anti-slop.ts — do not edit by hand.
`
  const upstreamLicense = readFileSync(path.join(cloneDir, "LICENSE"), "utf8")
  const license = `# anti-slop license

The bundled \`plugin.mjs\` is a build of
[anti-slop](https://github.com/dmmulroy/anti-slop) at commit ${commit},
with its \`@oxlint/plugins\` dependency (MIT) inlined.

${upstreamLicense}`
  const declaration = `// Generated by scripts/vendor-anti-slop.ts — do not edit by hand.
interface AntiSlopRule {
  readonly create: (context: never) => Record<string, never>
}

declare const antiSlopPlugin: {
  readonly meta: { readonly name: string }
  readonly rules: { readonly [ruleName: string]: AntiSlopRule }
}

export default antiSlopPlugin
`

  writeFileSync(path.join(outDir, "plugin.mjs"), banner + bundle)
  writeFileSync(path.join(outDir, "plugin.d.mts"), declaration)
  writeFileSync(path.join(outDir, "license.md"), license)
  console.info(`Vendored anti-slop@${commit} to ${outDir}`)
} finally {
  rmSync(cloneDir, { force: true, recursive: true })
}
