/**
 * Re-vendors third-party oxlint plugins into the presets that ship them.
 *
 * Some plugins are deliberately not published to npm — their distribution model is "copy the source
 * into your repo" — so Adamantite ships a bundled build instead of declaring a dependency. Each
 * bundle inlines the plugin's dependencies so the vendored file is fully self-contained. Those
 * inlined versions are pinned by the upstream lockfile; if an upstream ever drops its lockfile, a
 * re-vendor at the same pinned ref can inline different dependency versions, so read re-vendor
 * diffs with that in mind.
 *
 * Usage: node scripts/vendor-plugins.ts [name]
 *
 * Clones each upstream at its pinned commit, installs its dependencies, bundles the entry point to
 * ESM, and rewrites plugin.mjs, plugin.d.mts, and license.md in the preset's directory. After
 * bumping a pinned ref, review the upstream diff and update the rules in the owning preset if rules
 * were added, removed, or renamed (the preset's drift test will catch a mismatch).
 */
import { execFile } from "node:child_process"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"
import { promisify } from "node:util"
import * as Schema from "effect/Schema"
import { build } from "tsdown"

const execFileAsync = promisify(execFile)
const maxCommandOutputBytes = 10 * 1024 * 1024

const UpstreamPackageJson = Schema.Struct({ packageManager: Schema.String })
const decodeUpstreamPackageJson = Schema.decodeUnknownSync(UpstreamPackageJson)

interface VendoredPlugin {
  /**
   * Bundle entry point, relative to the upstream repository root.
   */
  readonly entry: string
  readonly name: string
  /**
   * Output directory, relative to this repository's root.
   */
  readonly outDir: string
  readonly pinnedRef: string
  readonly repoUrl: string
}

const VENDORED_PLUGINS: VendoredPlugin[] = [
  {
    entry: "src/index.ts",
    name: "anti-slop",
    outDir: "presets/lint/vendor/antislop",
    pinnedRef: "446268e5d15baa968eaec669ff65358d36ae6259",
    repoUrl: "https://github.com/dmmulroy/anti-slop.git",
  },
]

async function run(command: string, args: string[], cwd: string) {
  return execFileAsync(command, args, { cwd, maxBuffer: maxCommandOutputBytes })
}

async function installUpstreamDependencies(cwd: string) {
  const packageJson = decodeUpstreamPackageJson(
    JSON.parse(await readFile(path.join(cwd, "package.json"), "utf8"))
  )
  const packageManager = packageJson.packageManager

  if (!/^pnpm@\d/.test(packageManager)) {
    throw new Error(`Unsupported vendored plugin package manager: ${packageManager}`)
  }

  await run("pnpm", ["dlx", packageManager, "install", "--prod", "--frozen-lockfile"], cwd)
}

async function bundlePlugin(plugin: VendoredPlugin, cloneDir: string) {
  const bundleDir = path.join(cloneDir, ".adamantite-build")

  await build({
    clean: true,
    config: false,
    cwd: cloneDir,
    deps: {
      alwaysBundle: [/.*/],
      onlyImport: [],
    },
    dts: false,
    entry: [plugin.entry],
    format: "esm",
    logLevel: "silent",
    outDir: bundleDir,
    outExtensions: () => ({ js: ".mjs" }),
    platform: "node",
  })

  const entryName = `${path.basename(plugin.entry, path.extname(plugin.entry))}.mjs`
  return readFile(path.join(bundleDir, entryName), "utf8")
}

async function vendorPlugin(plugin: VendoredPlugin) {
  const outDir = path.join(import.meta.dirname, "..", plugin.outDir)
  const cloneDir = await mkdtemp(path.join(tmpdir(), `${plugin.name}-`))

  try {
    await run("git", ["clone", plugin.repoUrl, "."], cloneDir)
    await run("git", ["checkout", plugin.pinnedRef], cloneDir)
    const { stdout: revParse } = await run("git", ["rev-parse", "HEAD"], cloneDir)
    const commit = revParse.trim()

    // Install the plugin's dependencies so the bundler can inline them.
    await installUpstreamDependencies(cloneDir)

    // Strip temporary clone paths from module comments so re-vendoring produces stable diffs.
    const cloneDirPattern = new RegExp(`^// \\S*${path.basename(cloneDir)}/`, "gmu")
    const rawBundle = await bundlePlugin(plugin, cloneDir)
    const bundle = rawBundle.replace(cloneDirPattern, "// ")
    const banner = `// Vendored build of the ${plugin.name} oxlint plugin.
// Source: ${plugin.repoUrl.replace(/\.git$/, "")} (MIT) at commit ${commit}.
// Its dependencies (MIT) are inlined so this file is self-contained.
// See license.md for the full license text.
//
// Generated by scripts/vendor-plugins.ts — do not edit by hand.
`
    const upstreamLicense = await readFile(path.join(cloneDir, "LICENSE"), "utf8")
    const license = `# ${plugin.name} license

The bundled \`plugin.mjs\` is a build of
[${plugin.name}](${plugin.repoUrl.replace(/\.git$/, "")}) at commit ${commit},
with its dependencies (MIT) inlined.

${upstreamLicense}`
    const declaration = `// Generated by scripts/vendor-plugins.ts — do not edit by hand.
interface VendoredPluginRule {
  readonly create: (context: never) => Record<string, never>
}

declare const vendoredPlugin: {
  readonly meta: { readonly name: string }
  readonly rules: { readonly [ruleName: string]: VendoredPluginRule }
}

export default vendoredPlugin
`

    await mkdir(outDir, { recursive: true })
    await writeFile(path.join(outDir, "plugin.mjs"), banner + bundle)
    await writeFile(path.join(outDir, "plugin.d.mts"), declaration)
    await writeFile(path.join(outDir, "license.md"), license)
    console.info(`Vendored ${plugin.name}@${commit} to ${outDir}`)
  } finally {
    // Keep a cleanup failure from masking the clone, install, or bundle error.
    await rm(cloneDir, { force: true, recursive: true }).catch(() => null)
  }
}

const selectedName = process.argv[2]
const plugins = selectedName
  ? VENDORED_PLUGINS.filter((plugin) => plugin.name === selectedName)
  : VENDORED_PLUGINS

if (plugins.length === 0) {
  throw new Error(`No vendored plugin named ${selectedName}`)
}

await Promise.all(plugins.map((plugin) => vendorPlugin(plugin)))
