/**
 * Re-vendors third-party oxlint plugins into the presets that ship them.
 *
 * Some plugins are deliberately not published to npm — their distribution model is "copy the source
 * into your repo" — so Adamantite ships a bundled build instead of declaring a dependency. Each
 * bundle inlines the plugin's dependencies so the vendored file is fully self-contained. Those
 * inlined versions are pinned by the upstream lockfile; if an upstream ever drops its lockfile, a
 * re-vendor at the same pinned ref can inline different dependency versions, so read re-vendor
 * diffs with that in mind.
 *
 * Usage: bun run scripts/vendor-plugins.ts [name]
 *
 * Clones each upstream at its pinned commit, installs its dependencies, bundles the entry point to
 * ESM, and rewrites plugin.mjs, plugin.d.mts, and license.md in the preset's directory. After
 * bumping a pinned ref, review the upstream diff and update the rules in the owning preset if rules
 * were added, removed, or renamed (the preset's drift test will catch a mismatch).
 */
import { mkdtempSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { $ } from "bun"

interface VendoredPlugin {
  /**
   * Bundle entry point, relative to the upstream repository root.
   */
  readonly entry: string
  readonly name: string
  /**
   * Output directory, relative to this repository's root.
   */
  readonly outDir: string
  readonly pinnedRef: string
  readonly repoUrl: string
}

const VENDORED_PLUGINS: VendoredPlugin[] = [
  {
    entry: "src/index.ts",
    name: "anti-slop",
    outDir: "presets/lint/antislop",
    pinnedRef: "446268e5d15baa968eaec669ff65358d36ae6259",
    repoUrl: "https://github.com/dmmulroy/anti-slop.git",
  },
]

async function vendorPlugin(plugin: VendoredPlugin) {
  const outDir = path.join(import.meta.dirname, "..", plugin.outDir)
  const cloneDir = mkdtempSync(path.join(tmpdir(), `${plugin.name}-`))

  try {
    await $`git clone ${plugin.repoUrl} .`.cwd(cloneDir).quiet()
    await $`git checkout ${plugin.pinnedRef}`.cwd(cloneDir).quiet()
    const revParse = await $`git rev-parse HEAD`.cwd(cloneDir).text()
    const commit = revParse.trim()

    // Install the plugin's dependencies so the bundler can inline them.
    await $`bun install --production`.cwd(cloneDir).quiet()

    const build = await Bun.build({
      entrypoints: [path.join(cloneDir, plugin.entry)],
      format: "esm",
      target: "node",
    })

    if (!build.success) {
      throw new Error(`Bundling ${plugin.name} failed: ${build.logs.map(String).join("\n")}`)
    }

    const [output] = build.outputs

    // Bun emits a `// <path>` comment per bundled module, relative to the output location — which
    // points into the temp clone dir and differs per machine. Trim the prefix so re-vendoring
    // produces stable diffs.
    const cloneDirPattern = new RegExp(`^// \\S*${path.basename(cloneDir)}/`, "gmu")
    const rawBundle = await output.text()
    const bundle = rawBundle.replace(cloneDirPattern, "// ")
    const banner = `// Vendored build of the ${plugin.name} oxlint plugin.
// Source: ${plugin.repoUrl.replace(/\.git$/, "")} (MIT) at commit ${commit}.
// Its dependencies (MIT) are inlined so this file is self-contained.
// See license.md for the full license text.
//
// Generated by scripts/vendor-plugins.ts — do not edit by hand.
`
    const upstreamLicense = await Bun.file(path.join(cloneDir, "LICENSE")).text()
    const license = `# ${plugin.name} license

The bundled \`plugin.mjs\` is a build of
[${plugin.name}](${plugin.repoUrl.replace(/\.git$/, "")}) at commit ${commit},
with its dependencies (MIT) inlined.

${upstreamLicense}`
    const declaration = `// Generated by scripts/vendor-plugins.ts — do not edit by hand.
interface VendoredPluginRule {
  readonly create: (context: never) => Record<string, never>
}

declare const vendoredPlugin: {
  readonly meta: { readonly name: string }
  readonly rules: { readonly [ruleName: string]: VendoredPluginRule }
}

export default vendoredPlugin
`

    await Bun.write(path.join(outDir, "plugin.mjs"), banner + bundle)
    await Bun.write(path.join(outDir, "plugin.d.mts"), declaration)
    await Bun.write(path.join(outDir, "license.md"), license)
    console.info(`Vendored ${plugin.name}@${commit} to ${outDir}`)
  } finally {
    // nothrow so a cleanup failure cannot mask the real error from clone, install, or bundle.
    await $`rm -rf ${cloneDir}`.nothrow()
  }
}

const selectedName = process.argv[2]
const plugins = selectedName
  ? VENDORED_PLUGINS.filter((plugin) => plugin.name === selectedName)
  : VENDORED_PLUGINS

if (plugins.length === 0) {
  throw new Error(`No vendored plugin named ${selectedName}`)
}

await Promise.all(plugins.map((plugin) => vendorPlugin(plugin)))
